### ISSUE TITLE
256x256 sizes?

### ISSUE THREAD

**Issue by sagjig** [svew/spybotics-icons#1]
Hey, it's really cool someone could pull these from the game - I noticed on some of your other repos you had larger versions of these available; do you mind also uploading those 256x256 sized sprites?

Thanks in advance!

**Comment by svew** [comment]
Thanks I'm glad it's appreciated! 😁 I uploaded a 256x256 sprite sheet, if you're looking to get them as individual sprites you should be able to crop them using your favorite image editor
